source $VIMRUNTIME/defaults.vim

syntax enable
filetype plugin on
filetype indent on

set number
set relativenumber

set autoread
set mouse=
set timeoutlen=500

set cursorline
set laststatus=2
set ruler
set showcmd
set showmatch

set wildmenu
set wildmode=full
set wildoptions=fuzzy

" A buffer becomes hidden when it is abandoned
set hidden

set hlsearch
set ignorecase
set incsearch
set smartcase

set autoindent
set breakindent
set smartindent

set expandtab
set shiftwidth=4
set smarttab
set softtabstop=4
set tabstop=4

set scrolloff=4
set sidescrolloff=8

set splitbelow
set splitright

set belloff=all
set novisualbell

set encoding=utf8

" Use Unix as the standard file type
set fileformats=unix,dos

set nobackup
set nowritebackup
set noswapfile

set background=dark
if has('termguicolors')
    set termguicolors
endif
try
    packadd! everforest
    colorscheme everforest
    let g:airline_theme = 'everforest'
catch
endtry

if &term =~ 'xterm\|tmux\|win'
    " INSERT mode
    let &t_SI = "\<esc>[6 q"
    " REPLACE mode
    let &t_SR = "\<esc>[4 q"
    " NORMAL mode
    let &t_EI = "\<esc>[2 q"
endif

" Set <space> as leader
let mapleader = ' '

runtime! modules/keymap.vim
