[starship.files]
"starship.toml" = { target = "~/.config/starship.toml", type = "symbolic" }

[nvim.files]
nvim = "~/.config/nvim"

[joshuto.files]
joshuto = "~/.config/joshuto"

[shell.files]
git = "~/.gitconfig"
vimrc = "~/.vimrc"

[idea.files]
ideavimrc = { target = "~/.ideavimrc", type = "symbolic" }

[pwsh.files]
powershell = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[helix.files]
helix = "~/.config/helix"
