[starship.files]
starship = "~/.config/starship.toml"

[nvim.files]
nvim = "~/.config/nvim"

[git.files]
git = "~/.gitconfig"

[idea.files]
ideavimrc = { target = "~/.ideavimrc", type = "symbolic" }

[pwsh.files]
powershell = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[pwsh.variables]
scoop = true

[lazygit.files]
lazygit = { target = "~/.config/lazygit/config.yml", type = "symbolic" }

[yazi.files]
yazi = { target = "~/.config/yazi", type = "symbolic" }

[wezterm.files]
wezterm = "~/.config/wezterm"

[nushell.files]
nushell = "~/.config/nushell"

[bat.files]
bat = "~/.config/bat"

[rio.files]
rio = "~/.config/rio"

[tmux.files]
"tmux/tmux.conf" = "~/.tmux.conf"

[fish.files]
"fish/conf.d/alias.fish" = { target = "~/.config/fish/conf.d/alias.fish", type = "symbolic" }
"fish/conf.d/brew.fish" = { target = "~/.config/fish/conf.d/brew.fish", type = "symbolic", if = "(is_executable '/opt/homebrew/bin/brew')" }
"fish/conf.d/fzf.fish" = { target = "~/.config/fish/conf.d/fzf.fish", type = "symbolic", if = "(command_success 'command -v fzf >/dev/null 2>&1 || test -x /opt/homebrew/bin/fzf')" }
"fish/conf.d/starship.fish" = { target = "~/.config/fish/conf.d/starship.fish", type = "symbolic", if = "(command_success 'command -v starship >/dev/null 2>&1 || test -x /opt/homebrew/bin/starship')" }
"fish/conf.d/yazi.fish" = { target = "~/.config/fish/conf.d/yazi.fish", type = "symbolic", if = "(command_success 'command -v yazi >/dev/null 2>&1 || test -x /opt/homebrew/bin/yazi')" }
"fish/conf.d/zoxide.fish" = { target = "~/.config/fish/conf.d/zoxide.fish", type = "symbolic", if = "(command_success 'command -v zoxide >/dev/null 2>&1 || test -x /opt/homebrew/bin/zoxide')" }
