[starship.files]
starship = "~/.config/starship.toml"

[nvim.files]
nvim = "~/.config/nvim"

[joshuto.files]
joshuto = "~/.config/joshuto"

[shell.files]
git = "~/.gitconfig"
vimrc = "~/.vimrc"

[idea.files]
ideavimrc = { target = "~/.ideavimrc", type = "symbolic" }

[pwsh.files]
powershell = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[pwsh.variables]
scoop = true

[helix.files]
helix = "~/.config/helix"

[lazygit.files]
lazygit = { target = "~/.config/lazygit/config.yml", type = "symbolic" }

[yazi.files]
yazi = { target = "~/.config/yazi", type = "symbolic" }

[gitui.files]
gitui = "~/.config/gitui"

[wezterm.files]
wezterm = "~/.config/wezterm"
